services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=${MONGO_URI}
    env_file:
      - .env
    volumes:
      - ./server:/app
    depends_on:
      - mongo
    command: sh -c "npm install && npm start"

volumes:
  mongo_data: