services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    profiles:
      - dev

  server:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=${MONGO_URI}
    env_file:
      - .env
    volumes:
      - ./server:/app
    depends_on:
      - mongo
    command: sh -c "npm install && npm start"
    profiles:
      - dev

  mongo_prod:
    image: mongo
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db
    profiles:
      - prod

  server_prod:
    build: ./server
    expose:
      - "8080"
    environment:
      - MONGO_URI=${MONGO_URI}
    env_file:
      - .env
    volumes:
      - ./server:/app
    depends_on:
      - mongo
    command: sh -c "npm install && npm start"
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.full_js_back.rule=Host(`full-js.flo-isk.fr`) && PathPrefix(`/`)"
      - "traefik.http.routers.full_js_back.entrypoints=websecure"
      - "traefik.http.routers.full_js_back.tls=true"
      - "traefik.http.routers.full_js_back.tls.certresolver=myresolver"
      - "traefik.docker.network=traefik-net"
    restart: always
    profiles:
      - prod

volumes:
  mongo_data:

networks:
  traefik-net:
      external: true